#!/bin/sh
set -ea

_stopStrapi() {
  echo "Stopping strapi"
  kill -SIGINT "$strapiPID"
  wait "$strapiPID"
}

trap _stopStrapi SIGTERM SIGINT

cd /usr/src/api

APP_NAME=${APP_NAME:-strapi-app}
DATABASE_CLIENT=${DATABASE_CLIENT:-mongo}
DATABASE_HOST=${DATABASE_HOST:-localhost}
DATABASE_PORT=${DATABASE_PORT:-27017}
DATABASE_NAME=${DATABASE_NAME:-strapi}
DATABASE_USERNAME=${DATABASE_USERNAME:-}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-}
DATABASE_AUTHENTICATION_DATABASE=${DATABASE_AUTHENTICATION_DATABASE:-admin}
DATABASE_SRV=${DATABASE_SRV:-false}
DATABASE_SSL=${DATABASE_SSL:-false}
EXTRA_ARGS=${EXTRA_ARGS:-}

echo $DATABASE_HOST
echo "PROMP"

yarn start &

strapiPID=$!
wait "$strapiPID"